
import Head from 'next/head'
import Image from 'next/image'
//import React, { useEffect } from "react"
import styles from '../styles/Home.module.css'

export default function Home() {

  const handleWindowRedirect = (e) => {
    e.preventDefault()
    window.location.href = "https://rnbwapp.com/"
  }

  const handleTimedRedirect = (e) => {
    e.preventDefault()
    setTimeout(() => window.location.href = "https://rnbwapp.com/", 1000)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rainbow App Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rainbow App Links
        </h1>

        <p className={styles.description}>
          Test various Rainbow App Link flows
        </p>

        <div className={styles.grid}>
          <a href="https://rnbwapp.com/" className={styles.card}>
            <h2>Universal Link &rarr;</h2>
            <p>Test the rnbwapp.com universal link href</p>
          </a>

          <a href="rainbow://" className={styles.card}>
            <h2>Deep Link &rarr;</h2>
            <p>Test the rainbow:// deep link URI scheme href</p>
          </a>

          <a href="" onClick={handleWindowRedirect} className={styles.card}>
            <h2>Window Redirect &rarr;</h2>
            <p>Set the window.location.href to rnbwapp.com</p>
          </a>

          <a href="" onClick={handleTimedRedirect} className={styles.card}>
            <h2>Timed Redirect &rarr;</h2>
            <p>Set the window.location.href to rnbwapp.com after 1s</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
