
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const handleWindowRedirect = (e) => {
    e.preventDefault()
    window.location.href = e.target.href || e.target.parentElement.href
  }

  const handleTimedRedirect = (e) => {
    e.preventDefault()
    setTimeout(() => window.location.href = e.target.href || e.target.parentElement.href, 1000)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rainbow App Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rainbow App Links
        </h1>

        <p className={styles.description}>
          Test various Rainbow App Link flows
        </p>

        <div className={styles.grid}>
          <a href="https://rnbwapp.com/" className={styles.card}>
            <h2>Universal Link &rarr;</h2>
            <p>Test the rnbwapp.com universal link href</p>
          </a>

          <a href="rainbow://" className={styles.card}>
            <h2>Deep Link &rarr;</h2>
            <p>Test the rainbow:// deep link URI scheme href</p>
          </a>

          <a href="https://rnbwapp.com/" onClick={handleWindowRedirect} className={styles.card}>
            <h2>Window Redirect &rarr;</h2>
            <p>Set the window.location.href to rnbwapp.com</p>
          </a>

          <a href="https://rnbwapp.com/" onClick={handleTimedRedirect} className={styles.card}>
            <h2>Timed Redirect &rarr;</h2>
            <p>Set the window.location.href to rnbwapp.com after 1s</p>
          </a>

          <a href="https://rnbwapp.com/wc" onClick={handleWindowRedirect} className={styles.card}>
            <h2>WC Redirect &rarr;</h2>
            <p>Set the window.location.href to rnbwapp.com/wc</p>
          </a>

          <a href="https://rnbwapp.com/wc" onClick={handleTimedRedirect} className={styles.card}>
            <h2>WC Timed Redirect &rarr;</h2>
            <p>Set the window.location.href to rnbwapp.com/wc after 1s</p>
          </a>

          <a href="https://rnbwapp.com/token?addr=eth" className={styles.card}>
            <h2>Token &rarr;</h2>
            <p>Open the universal link for the ETH token view</p>
          </a>

          <a href="https://rnbwapp.com/imhiring.eth" className={styles.card}>
            <h2>Profile &rarr;</h2>
            <p>Open the universal link for an ENS profile</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
